import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
    title: "Facewash",
    price: "355",
    rating : 4,
    categoryName: "Facewash",
  },
  {
    _id: uuid(),
    img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653331169/facewash-2_okmgtz.png',
    title: "HairSpray",
    price: "400",
    rating: 3,
    categoryName: "HairSpray",
  },
  {
    _id: uuid(),
    img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
    title: "Hairspray",
    price: "300",
    rating: 3,
    categoryName: "Hairspray",
  },
  {
    _id: uuid(),
    img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
    title: "Combos",
    price: "800",
    rating: 3.8,
    categoryName: "Combos",
  },
  {
    _id: uuid(),
    img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
    title: "Facewash",
    price: "200",
    rating: 4.2,
    categoryName: "Facewash",
  },
  {
    _id: uuid(),
    img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
    title: "Combos",
    price: "900",
    rating: 2,
    categoryName: "Combos",
  },
  // {
  //   _id: uuid(),
  //   img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
  //   title: "facewash",
  //   price: "225",
  //   rating: 3.2,
  //   categoryName: "fiction",
  // },
  // {
  //   _id: uuid(),
  //   img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
  //   title: "Combos",
  //   price: "1000",
  //   rating: 5,
  //   categoryName: "fiction",
  // },
  // {
  //   _id: uuid(),
  //   img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
  //   title: "Hairspray",
  //   price: "330",
  //   rating:4.4,
  //   categoryName: "fiction",
  // },
  // {
  //   _id: uuid(),
  //   img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
  //   title: "Hairspray",
  //   price: "280",
  //   rating: 4.8,
  //   categoryName: "fiction",
  // },
  // {
  //   _id: uuid(),
  //   img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
  //   title: "Combos",
  //   price: "2400",
  //   rating: 5,
  //   categoryName: "fiction",
  // },
  // {
  //   _id: uuid(),
  //   img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
  //   title: "Facewash",
  //   price: "440",
  //   rating: 3.2,
  //   categoryName: "fiction",
  // },
  // {
  //   _id: uuid(),
  //   img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
  //   title: "Combos",
  //   price: "1500",
  //   rating: 3,
  //   categoryName: "fiction",
  // },
  // {
  //   _id: uuid(),
  //   img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
  //   title: "Combos",
  //   price: "3500",
  //   rating: 2.8,
  //   categoryName: "fiction",
  // },
  // {
  //   _id: uuid(),
  //   img: 'https://res.cloudinary.com/df5hhvtdp/image/upload/v1653327347/final-draft_d6zv0s.png',
  //   title: "Combos",
  //   price: "2800",
  //   rating: 3.2,
  //   categoryName: "fiction",
  // },
];
